services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
    networks:
      - ingestion-net

  broker:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.25
    container_name: quarkus-broker
    restart: always
    environment:
      - AMQ_USER
      - AMQ_PASSWORD
    ports:
      - "8161:8161"
      - "6161:6161"
      - "5672:5672"
    networks:
      - ingestion-net

  async-api-endpoint:
    build:
      context: ../java/async-api-endpoint
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    container_name: async-api-endpoint
    restart: always
    volumes:
      - ${HOME_PATH}/dockervolume/ingestion:${CONTAINER_DOWNLOAD_DIR}
    environment:
      - QUEUE_NAME
      - QUARKUS_QPID_JMS_USERNAME
      - QUARKUS_QPID_JMS_PASSWORD
      - QUARKUS_QPID_JMS_URL=amqp://quarkus-broker:5672
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL
      - QUARKUS_DATASOURCE_USERNAME
      - QUARKUS_DATASOURCE_PASSWORD
    ports:
      - "8080:8080"
    networks:
      - ingestion-net

  ingestion-manager:
    build:
      context: ../java/ingestion-manager
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    container_name: ingestion-manager
    volumes:
      - ${HOME_PATH}/dockervolume/ingestion:${CONTAINER_DOWNLOAD_DIR}
    environment:
      - QUEUE_NAME
      - CONTAINER_DOWNLOAD_DIR
      - QUARKUS_QPID_JMS_USERNAME
      - QUARKUS_QPID_JMS_PASSWORD
      - QUARKUS_QPID_JMS_URL=amqp://quarkus-broker:61616
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL
      - QUARKUS_DATASOURCE_USERNAME
      - QUARKUS_DATASOURCE_PASSWORD
    networks:
      - ingestion-net

networks:
  ingestion-net:
    driver: bridge
