services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
    networks:
      - ingestion-net

  ingestion-manager:
    build:
      context: ../ingestion-manager
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    container_name: ingestion-manager
    volumes:
      - ${HOME_PATH}/dockervolume/ingestion:${CONTAINER_DOWNLOAD_DIR}
    environment:
      - CONTAINER_DOWNLOAD_DIR
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL
      - QUARKUS_DATASOURCE_USERNAME
      - QUARKUS_DATASOURCE_PASSWORD
    ports:
      - "8080:8080"
    networks:
      - ingestion-net

networks:
  ingestion-net:
    driver: bridge
