services:
  broker:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.25
    container_name: quarkus-broker
    environment:
      - AMQ_USER
      - AMQ_PASSWORD
    ports:
      - "8161:8161"
      - "6161:6161"
      - "5672:5672"
    networks:
      - ingestion-net

  async-api-endpoint:
    build:
      context: ../java/async-api-endpoint
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    container_name: async-api-endpoint
    volumes:
      - ${HOME_PATH}/dockervolume/ingestion:${DOWNLOAD_DIR}
    environment:
      - DATA_PATH=/home/default
      - QUEUE_NAME
      - QUARKUS_QPID_JMS_USERNAME
      - QUARKUS_QPID_JMS_PASSWORD
      - QUARKUS_QPID_JMS_URL=amqp://quarkus-broker:5672
    ports:
      - "8080:8080"
    networks:
      - ingestion-net

  ingestion-manager:
    build:
      context: ../java/ingestion-manager
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    container_name: ingestion-manager
    volumes:
      - ${HOME_PATH}/dockervolume/ingestion:${DOWNLOAD_DIR}
    environment:
      - QUEUE_NAME
      - QUARKUS_QPID_JMS_USERNAME
      - QUARKUS_QPID_JMS_PASSWORD
      - QUARKUS_QPID_JMS_URL=amqp://quarkus-broker:61616
      - DOWNLOAD_DIR
    networks:
      - ingestion-net

networks:
  ingestion-net:
    driver: bridge
