services:
  spark-master:
    image: bitnami/spark:3.4
    volumes:
      - /Users/ruixue/dockervolume/spark:/opt/bitnami/spark/jobs
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_NO_DAEMONIZE=yes
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
